### ISSUE TITLE
Schedule update: a soft deadline, helper onboarding and installation help

### ISSUE THREAD

**Issue by naoe-tatara** [coderefinery/2021-05-10-workshop#2]
Zulip Workshop stream "2021 spring workshop", Mar 12 6:19 PM

Can we set a (soft) registration deadline to the end of 28th CET so that we can work on how many individual learners we can accept on 29th Mon and can start to send acceptance emails?

Helper onboarding and installation help following
April Wed 7th 13:00-14:00 CET (tbd), Thu 8th 13:30-14:30 CET? And installation help following?

**Comment by naoe-tatara** [comment]
Due to the change in the schedule of this workshop, edited the title.

**Comment by bast** [comment]
Closed in #7.
