### ISSUE TITLE
question about top-down and bottom-up from day 6

### ISSUE THREAD

**Issue by dianaiusan** [coderefinery/2021-05-10-workshop#59]
@bast and @annefou,

There was a question in the Q&A from day 6 which I did not answer.
Someone was asking: "What does top-down and bottom-up means here?" (in the context of modular code development).

I was thinking I could add this answer:

"
Top-down and bottom-up are two strategies for approching software development. In the top-down approach, also referred to as stepwise refinement, one starts with the overview of the code, in this case it would be drafting a `main` file which calls different subroutines and functions. One then builds from there and implements different subroutines or functions, typically in different files. The disadvantage of this approach is that the code is not easily testable and usable until the entire implementation is complete.

In the bottom-up approach, one puts together different codes or scripts that may be used on their own as well. External libraries can also be viewed as a piece of this software "puzzle". The advantage of this approach is that it is easily testable at the early stage of the programming process. On the other hand, it may be harder to link these different parts and produce a coherent code.
"

Any suggestions or comments? I can PR if we agree upon this.
/Diana

**Comment by bast** [comment]
It's a very good explanation! Thanks!
